# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  plugin-name: 
    description: 'plugin name, defaults to git repo name where this action is triggered'
    required: true
  upstream-krew-index-owner:
    description: 'the owner of upstream krew-index repo'  
    required: true
    default: 'rajatjin'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.plugin-name }}
